# Generated by Django 4.1 on 2022-09-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0002_remove_user_full_name_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='qualifications',
        ),
    ]
