# Generated by Django 4.1 on 2022-09-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0003_remove_applicant_qualifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='company',
        ),
    ]
