# Generated by Django 4.1 on 2022-10-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0007_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
