# Generated by Django 4.1 on 2022-10-27 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0009_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateField()),
                ('approved', models.BooleanField(default=False)),
                ('date_approved', models.DateField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker.applicant')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_seeker.staff')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker.job')),
            ],
        ),
    ]
