# Generated by Django 4.1 on 2022-11-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0011_application_cover_letter_job_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_applied',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_approved',
            field=models.DateTimeField(),
        ),
    ]
