# Generated by Django 4.1 on 2022-11-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0012_alter_application_date_applied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
