apiVersion: v1
kind: Service
metadata:
  name: testauto
  namespace: namespace-workflow-1731586290690
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: testauto
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000